import { db } from "@workspace/db";
import { tilesTable } from "@workspace/db";

const tiles = [
  // ─── Ceramic Floor Tiles ───
  {
    name: "Arctic White Floor",
    sku: "SCF-001",
    category: "ceramic_floor",
    finish: "matte",
    room: "living_room",
    size: "600x600",
    pricePerSqft: "45",
    color: "white",
    pattern: "solid",
    description: "Clean, crisp arctic white ceramic floor tile with a subtle matte finish. Timeless and versatile — pairs beautifully with any interior style.",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&h=300&fit=crop&q=80",
    collection: "Arctic Series",
    isNew: false,
    isBestSeller: true,
    rating: "4.5",
    reviewCount: 328,
    tags: ["floor", "white", "matte", "living-room", "bedroom"],
    aiEmbeddingText: "white matte ceramic floor tile 600x600 living room bedroom neutral clean contemporary minimalist",
  },
  {
    name: "Carrara Marble Effect",
    sku: "SCF-002",
    category: "ceramic_floor",
    finish: "glossy",
    room: "living_room",
    size: "800x800",
    pricePerSqft: "85",
    color: "white-grey",
    pattern: "marble-veins",
    description: "Luxurious Carrara marble-effect ceramic tile with authentic grey veining. Brings the opulence of Italian marble at a fraction of the cost.",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=300&h=300&fit=crop&q=80",
    collection: "Marmo Luxe",
    isNew: false,
    isBestSeller: true,
    rating: "4.8",
    reviewCount: 512,
    tags: ["marble-look", "luxury", "glossy", "living-room", "premium"],
    aiEmbeddingText: "marble effect white grey glossy ceramic large format luxury premium living room foyer",
  },
  {
    name: "Terracotta Earth",
    sku: "SCF-003",
    category: "ceramic_floor",
    finish: "rustic",
    room: "living_room",
    size: "600x600",
    pricePerSqft: "55",
    color: "terracotta",
    pattern: "textured-natural",
    description: "Warm terracotta-inspired ceramic with an organic rustic texture. Evokes the earthy aesthetics of Indian heritage architecture and natural stone.",
    imageUrl: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=300&h=300&fit=crop&q=80",
    collection: "Earth & Stone",
    isNew: true,
    isBestSeller: false,
    rating: "4.3",
    reviewCount: 145,
    tags: ["terracotta", "rustic", "earthy", "natural", "warm"],
    aiEmbeddingText: "terracotta earthy rustic warm natural organic heritage living room bedroom outdoor traditional Indian",
  },
  // ─── Glazed Vitrified Tiles ───
  {
    name: "Midnight Onyx GVT",
    sku: "SGV-001",
    category: "glazed_vitrified",
    finish: "glossy",
    room: "living_room",
    size: "800x800",
    pricePerSqft: "120",
    color: "black",
    pattern: "vein-pattern",
    description: "Dramatic midnight black glazed vitrified tile with subtle onyx-like veining. Creates powerful visual statements in luxury spaces.",
    imageUrl: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=300&h=300&fit=crop&q=80",
    collection: "Noir Collection",
    isNew: true,
    isBestSeller: false,
    rating: "4.6",
    reviewCount: 89,
    tags: ["black", "luxury", "glossy", "dramatic", "premium", "feature-wall"],
    aiEmbeddingText: "black onyx dark dramatic luxury glossy glazed vitrified living room feature wall modern contemporary",
  },
  {
    name: "Sahara Beige GVT",
    sku: "SGV-002",
    category: "glazed_vitrified",
    finish: "matte",
    room: "bedroom",
    size: "600x1200",
    pricePerSqft: "95",
    color: "beige",
    pattern: "subtle-grain",
    description: "Elegant warm beige GVT with a calming matte finish and subtle natural grain texture. Perfect for creating serene bedroom retreats.",
    imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=300&h=300&fit=crop&q=80",
    collection: "Desert Sand",
    isNew: false,
    isBestSeller: true,
    rating: "4.4",
    reviewCount: 267,
    tags: ["beige", "warm", "matte", "bedroom", "serene", "large-format"],
    aiEmbeddingText: "beige warm matte large format glazed vitrified bedroom serene calm neutral elegant sophisticated",
  },
  {
    name: "Forest Oak Wood-Look",
    sku: "SGV-003",
    category: "glazed_vitrified",
    finish: "satin",
    room: "bedroom",
    size: "200x1200",
    pricePerSqft: "78",
    color: "oak-brown",
    pattern: "wood-plank",
    description: "Realistic oak wood-plank look GVT with warm brown tones and natural wood grain texture. All the beauty of wood, none of the maintenance.",
    imageUrl: "https://images.unsplash.com/photo-1562184552-997c461abbe6?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1562184552-997c461abbe6?w=300&h=300&fit=crop&q=80",
    collection: "Timberwood",
    isNew: true,
    isBestSeller: true,
    rating: "4.7",
    reviewCount: 389,
    tags: ["wood-look", "plank", "warm", "bedroom", "living-room", "natural"],
    aiEmbeddingText: "wood plank oak brown warm natural bedroom living room satin wood-look floor tile contemporary",
  },
  // ─── Polished Vitrified Tiles ───
  {
    name: "Crystal White PVT",
    sku: "SPV-001",
    category: "polished_vitrified",
    finish: "glossy",
    room: "living_room",
    size: "800x800",
    pricePerSqft: "110",
    color: "white",
    pattern: "polished-plain",
    description: "High-gloss polished vitrified tile with mirror-like surface. Premium light-reflecting properties enhance spaciousness in any room.",
    imageUrl: "https://images.unsplash.com/photo-1615529183098-19e0c9f3f9f4?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1615529183098-19e0c9f3f9f4?w=300&h=300&fit=crop&q=80",
    collection: "Crystal Shine",
    isNew: false,
    isBestSeller: true,
    rating: "4.5",
    reviewCount: 445,
    tags: ["white", "glossy", "reflective", "premium", "living-room", "foyer"],
    aiEmbeddingText: "white glossy polished mirror-like reflective light-enhancing premium luxury living room hall foyer",
  },
  {
    name: "Golden Travertine PVT",
    sku: "SPV-002",
    category: "polished_vitrified",
    finish: "glossy",
    room: "living_room",
    size: "600x1200",
    pricePerSqft: "130",
    color: "golden-cream",
    pattern: "travertine",
    description: "Royal golden travertine-effect PVT with warm cream-gold tones and natural stone veining. Exudes luxury and sophistication.",
    imageUrl: "https://images.unsplash.com/photo-1544083183-a5bc87cf5b14?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1544083183-a5bc87cf5b14?w=300&h=300&fit=crop&q=80",
    collection: "Royal Travertine",
    isNew: false,
    isBestSeller: false,
    rating: "4.6",
    reviewCount: 178,
    tags: ["gold", "luxury", "travertine", "premium", "royal", "living-room"],
    aiEmbeddingText: "golden travertine royal luxury premium glossy living room hall staircase sophisticated opulent",
  },
  // ─── Bathroom Tiles ───
  {
    name: "Aqua Blu Wall",
    sku: "SCW-001",
    category: "ceramic_wall",
    finish: "glossy",
    room: "bathroom",
    size: "300x600",
    pricePerSqft: "38",
    color: "blue",
    pattern: "subway",
    description: "Fresh aqua blue ceramic wall tile in classic subway format. Brings spa-like serenity and Mediterranean freshness to bathroom spaces.",
    imageUrl: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=300&h=300&fit=crop&q=80",
    collection: "Coastal Blue",
    isNew: false,
    isBestSeller: true,
    rating: "4.4",
    reviewCount: 521,
    tags: ["blue", "bathroom", "wall", "subway", "fresh", "spa"],
    aiEmbeddingText: "blue aqua ceramic wall tile bathroom subway fresh spa Mediterranean coastal cool serene",
  },
  {
    name: "Zen Grey Bathroom",
    sku: "SCW-002",
    category: "ceramic_wall",
    finish: "matte",
    room: "bathroom",
    size: "300x600",
    pricePerSqft: "42",
    color: "grey",
    pattern: "concrete-look",
    description: "Cool-toned grey matte ceramic wall tile with a refined concrete-look texture. Creates minimalist, spa-inspired bathroom environments.",
    imageUrl: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=300&h=300&fit=crop&q=80",
    collection: "Zen Collection",
    isNew: true,
    isBestSeller: false,
    rating: "4.3",
    reviewCount: 203,
    tags: ["grey", "bathroom", "concrete-look", "matte", "minimalist", "zen"],
    aiEmbeddingText: "grey matte concrete look bathroom wall tile minimalist zen spa contemporary Nordic Scandinavian",
  },
  {
    name: "Ivory Mosaic Accent",
    sku: "SCW-003",
    category: "ceramic_wall",
    finish: "glossy",
    room: "bathroom",
    size: "300x300",
    pricePerSqft: "52",
    color: "ivory",
    pattern: "mosaic",
    description: "Delicate ivory mosaic ceramic tile for accent walls and feature areas. Small format design creates visual depth and artisanal charm.",
    imageUrl: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=300&h=300&fit=crop&q=80",
    collection: "Mosaic Art",
    isNew: false,
    isBestSeller: false,
    rating: "4.2",
    reviewCount: 134,
    tags: ["mosaic", "ivory", "accent", "bathroom", "kitchen-backsplash", "artisan"],
    aiEmbeddingText: "ivory mosaic accent wall bathroom kitchen backsplash glossy small format artisan decorative",
  },
  // ─── Kitchen Tiles ───
  {
    name: "Chef's Granite Kitchen",
    sku: "SCF-004",
    category: "ceramic_floor",
    finish: "textured",
    room: "kitchen",
    size: "600x600",
    pricePerSqft: "48",
    color: "grey-speckled",
    pattern: "granite-look",
    description: "Slip-resistant textured granite-look ceramic tile for kitchens. Anti-skid surface ensures safety while grey speckled pattern conceals everyday stains.",
    imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=300&h=300&fit=crop&q=80",
    collection: "Kitchen Pro",
    isNew: false,
    isBestSeller: true,
    rating: "4.6",
    reviewCount: 298,
    tags: ["kitchen", "anti-skid", "granite-look", "textured", "practical", "grey"],
    aiEmbeddingText: "kitchen floor tile textured anti-skid granite look grey speckled practical hygienic slip resistant",
  },
  {
    name: "Metro White Backsplash",
    sku: "SCW-004",
    category: "ceramic_wall",
    finish: "glossy",
    room: "kitchen",
    size: "100x300",
    pricePerSqft: "35",
    color: "white",
    pattern: "metro-brick",
    description: "Classic white metro brick ceramic wall tile for kitchen backsplashes. Timeless subway brick pattern that complements any kitchen style from traditional to modern.",
    imageUrl: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=300&h=300&fit=crop&q=80",
    collection: "Metro Classic",
    isNew: false,
    isBestSeller: true,
    rating: "4.5",
    reviewCount: 467,
    tags: ["kitchen", "backsplash", "white", "metro", "subway", "timeless"],
    aiEmbeddingText: "white metro subway brick kitchen backsplash wall tile glossy classic timeless versatile clean",
  },
  // ─── Large Format Slabs ───
  {
    name: "Statuario Grande Slab",
    sku: "SLS-001",
    category: "large_slab",
    finish: "glossy",
    room: "living_room",
    size: "1200x2400",
    pricePerSqft: "185",
    color: "white-gold-veined",
    pattern: "statuario-marble",
    description: "Magnificent 1200x2400mm Statuario marble-effect slab. Fewer grout lines, seamless surfaces, and breathtaking scale. The pinnacle of luxury tile design.",
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=300&h=300&fit=crop&q=80",
    collection: "Coverstone Max",
    isNew: true,
    isBestSeller: true,
    rating: "4.9",
    reviewCount: 67,
    tags: ["large-slab", "marble", "luxury", "premium", "statuario", "seamless"],
    aiEmbeddingText: "large slab 1200x2400 statuario marble luxury premium seamless floor feature wall ultra-premium bungalow",
  },
  {
    name: "Charcoal Slate Slab",
    sku: "SLS-002",
    category: "large_slab",
    finish: "matte",
    room: "living_room",
    size: "1200x2400",
    pricePerSqft: "165",
    color: "charcoal",
    pattern: "slate-texture",
    description: "Bold charcoal large-format slab with natural slate-inspired texture. Makes an architectural statement in contemporary living rooms and commercial spaces.",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=300&h=300&fit=crop&q=80",
    collection: "Coverstone Max",
    isNew: true,
    isBestSeller: false,
    rating: "4.7",
    reviewCount: 43,
    tags: ["large-slab", "charcoal", "dark", "slate", "contemporary", "commercial"],
    aiEmbeddingText: "charcoal dark large slab matte slate texture contemporary living room feature wall architectural dramatic industrial",
  },
  // ─── Outdoor Tiles ───
  {
    name: "Stone Grip Outdoor",
    sku: "SOT-001",
    category: "ceramic_floor",
    finish: "textured",
    room: "outdoor",
    size: "600x600",
    pricePerSqft: "58",
    color: "sandstone",
    pattern: "rough-stone",
    description: "Heavy-duty slip-resistant outdoor ceramic tile with authentic sandstone look. UV-stable, frost-resistant, and engineered for Indian climate extremes.",
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&h=600&fit=crop&q=80",
    thumbnailUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=300&h=300&fit=crop&q=80",
    collection: "Outdoor Pro",
    isNew: false,
    isBestSeller: true,
    rating: "4.4",
    reviewCount: 312,
    tags: ["outdoor", "anti-skid", "UV-stable", "sandstone", "terrace", "garden"],
    aiEmbeddingText: "outdoor floor tile anti-skid slip resistant UV stable sandstone rough texture terrace garden balcony durable",
  },
];

async function seed() {
  console.log("Seeding tile catalog...");
  
  for (const tile of tiles) {
    await db
      .insert(tilesTable)
      .values(tile)
      .onConflictDoNothing();
  }
  
  console.log(`Seeded ${tiles.length} tiles successfully`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed error:", err);
  process.exit(1);
});
